// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Album { id: string, title: string, artist: string, track_count: number, artwork_path: string | null, }