// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Metadata { title: string, artist: string, song_artist: string | null, album: string, track_number: number | null, cd_number: number | null, year: number | null, genre: string | null, artwork_path: string | null, }
