// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Metadata } from "./Metadata";

export interface Track { id: string, path: string, metadata: Metadata, duration: number, }